# This owrkflow automaticlly runs all unit tests implemented using gtest every time a new release is created

name: All tests

# Run automatically every time a new release is created
on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  gtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Install gtest
        run: |
          cd /home/runner/work/NetworkTester/NetworkTester/gtest/googletest/
          mkdir build
          cd build/
          cmake ..
          sudo make install -j8

      - name: Compile test
        run: |
          cd /home/runner/work/NetworkTester/NetworkTester/gtest/
          mkdir build
          cd build/
          cmake ..
          make -j8

      - name: Create second certs
        run: |
          cd /home/runner/work/NetworkTester/NetworkTester/
          ./TlsCreateCertFiles.sh

      - name: Run all tests
        run: |
          cd /home/runner/work/NetworkTester/NetworkTester/gtest/
          ./RunAllTests.sh
