# This workflow automatically runs all unit tests implemented using gtest every time a new gtest tag is pushed

name: gtest

# Run automatically every time a new gtest tag is pushed
on:
  push:
    tags:
      - gtest-v*

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Create certs
        run: |
          cd /home/runner/work/NetworkTester/NetworkTester/
          ./TlsCreateCertFiles.sh

      - name: Install gtest
        run: |
          cd /home/runner/work/NetworkTester/NetworkTester/gtest/googletest/
          mkdir build
          cd build/
          cmake ..
          sudo make install -j8

      - name: Compile test
        run: |
          cd /home/runner/work/NetworkTester/NetworkTester/gtest/
          mkdir build
          cd build/
          cmake ..
          make -j8

      - name: Run all tests
        run: |
          cd /home/runner/work/NetworkTester/NetworkTester/gtest/
          ./RunAllTests.sh

      - name: Archive results JSON file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: gtest-complete-report
          path: /home/runner/work/NetworkTester/NetworkTester/gtest/results*.json
          if-no-files-found: error
