# This owrkflow automaticlly runs all unit tests implemented using gtest every time, the main branch is updated

name: gtest

# Runs every time, the main branch is updated
on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install gtest
        run: |
          git submodule update --init --recursive
          cd /home/runner/work/NetworkTester/NetworkTester/gtest/googletest/
          mkdir build
          cd build/
          cmake ..
          sudo make install -j4

      - name: Compile
        run: |
          cd /home/runner/work/NetworkTester/NetworkTester/gtest/
          mkdir build
          cd build/
          cmake ..
          make -j4

      - name: Create second certs
        run: |
          /home/runner/work/NetworkTester/NetworkTester/
          ./TlsCreateCertFiles.sh

      - name: Run all tests
        run: |
          cd /home/runner/work/NetworkTester/NetworkTester/gtest/
          ./RunAllTests.sh
