# This workflow automatically runs all unit tests implemented using gtest every time a new gtest tag is pushed

name: gtest

# Run automatically every time a new gtest tag is pushed
on:
  push:
    tags:
      - gtest-v*

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install necessary packages
        run: |
          sudo apt update -y
          sudo apt install -y build-essential cmake openssl libssl-dev

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Create certs
        run: ./TlsCreateCertFiles.sh

      - name: Install gtest
        run: |
          cd gtest/googletest
          mkdir build
          cd build
          cmake ..
          sudo make install -j8

      - name: Compile test
        run: |
          cd gtest
          mkdir build
          cd build
          cmake ..
          make -j8

      - name: Run all tests
        run: |
          cd gtest
          ./RunAllTests.sh

      - name: Archive results JSON file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: gtest-complete-report
          path: gtest/results.json
          if-no-files-found: error
