# This owrkflow automaticlly runs all unit tests implemented using gtest every time a new gtest tag is pushed

name: gtest

# Run automatically every time a new gtest tag is pushed
on:
  push:
    tags:
      - gtest-v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v3

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Install gtest
        run: |
          cd /home/runner/work/NetworkTester/NetworkTester/gtest/googletest/
          mkdir build
          cd build/
          cmake ..
          sudo make install -j8

      - name: Compile test
        run: |
          cd /home/runner/work/NetworkTester/NetworkTester/gtest/
          mkdir build
          cd build/
          cmake ..
          make -j8

      - name: Create second certs
        run: |
          cd /home/runner/work/NetworkTester/NetworkTester/
          ./TlsCreateCertFiles.sh

      - name: Run all tests
        run: |
          cd /home/runner/work/NetworkTester/NetworkTester/gtest/
          ./RunAllTests.sh

      - name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: "/home/runner/work/NetworkTester/NetworkTester/gtest/include/TestDefines.h"

      - name: File contents
        run: echo "File content - ${{ steps.read_file.outputs.contents }}"
